package com.entando.apiman.config;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.web.reactive.function.client.WebClient;

@Configuration
public class WebClientConfiguration {
	@Bean
	public WebClient webclient() {

		WebClient webClient = WebClient.builder().baseUrl("http://localhost:8080")
				.defaultCookie("cookieKey", "cookieValue")
				// .defaultHeaders(header -> header.setBasicAuth(userName, password))
				.defaultHeaders(header -> header.setBearerAuth("eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJGSjg2R2NGM2pUYk5MT2NvNE52WmtVQ0lVbWZZQ3FvcXRPUWVNZmJoTmxFIn0.eyJleHAiOjE2NjM1NjY0NjMsImlhdCI6MTY2MzU2NjIyMywiYXV0aF90aW1lIjoxNjYzNTU5OTYxLCJqdGkiOiIxN2NhYjMyNC1iMDIxLTRiNDgtYmIzZS0xNTIxYzI3MTQ4MzQiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODAvYXV0aC9yZWFsbXMvYXBpbWFuIiwiYXVkIjoiYWNjb3VudCIsInN1YiI6ImIyY2E0NmNiLWYzYWMtNDQzOS1hMmUwLWYzNjYyNzZjYzkxNSIsInR5cCI6IkJlYXJlciIsImF6cCI6ImFwaW1hbnVpIiwic2Vzc2lvbl9zdGF0ZSI6ImU3NTJmN2I2LTAzYjAtNGFiYi1hZTMzLTNjYzZjMjA3N2IyNCIsImFjciI6IjEiLCJhbGxvd2VkLW9yaWdpbnMiOlsiaHR0cDovL2xvY2FsaG9zdDo4MDgwIiwiaHR0cHM6Ly9sb2NhbGhvc3Q6ODQ0MyJdLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiIsImFwaXVzZXIiLCJkZWZhdWx0LXJvbGVzLWFwaW1hbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwiLCJzaWQiOiJlNzUyZjdiNi0wM2IwLTRhYmItYWUzMy0zY2M2YzIwNzdiMjQiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJnIGYiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJnb3ZpbmQiLCJnaXZlbl9uYW1lIjoiZyIsImZhbWlseV9uYW1lIjoiZiIsImVtYWlsIjoiZ292aW5kLm11bmRoZUBuZXd2aXNpb25zb2Z0d2FyZS5pbiJ9.AddmdIpFIFQIs7qGOF-N9Csaj6UqKn4vQcP86Gk-AkDculAD6GZaY4t4KI4lZxVka_OfAs3BSSPE6rurmQRpwlSmqfZ8wrH2pNpG2m6AqbQMvPWfjAVVSUydSiaHWixhlVx4NCkHGKSCNeD7BG_OWqb0dgGKSIj2UHmyOBL7hSk"))
				.build();
		return webClient;
	}

}